workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: cd cart_app && flutter pub get
      - name: Build iOS Simulator
        script: cd cart_app && flutter build ios --simulator --debug
    artifacts:
      - cart_app/build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - henriquefuentes@gmail.com
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android APK Build
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: cd cart_app && flutter pub get
      - name: Build Android APK
        script: cd cart_app && flutter build apk --release
    artifacts:
      - cart_app/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - henriquefuentes@gmail.com
        notify:
          success: true
          failure: true
